# Generated by Django 5.2.3 on 2025-06-21 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='The name of the bot, used for identification.', max_length=255, unique=True)),
                ('token', models.CharField(help_text='The token used to authenticate the bot with the Telegram API.', max_length=255, unique=True)),
                ('webhook_url', models.URLField(blank=True, help_text='The URL where the bot will receive updates from Telegram. If empty, the bot will not use webhooks.', max_length=1024)),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
