# Generated by Django 5.2.3 on 2025-06-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='secret_key',
            field=models.CharField(default='', help_text='A secret key used to verify requests from Telegram.', max_length=255),
            preserve_default=False,
        ),
    ]
